[platformio]
default_envs = teensy41
src_dir = final_serial_router_protocol_bridge

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
build_src_filter = +<*> -<esp_router.ino>
lib_deps = 
    # Add any libraries here if needed in the future

[env:native]
platform = native
test_framework = unity
# The native environment needs to find the parser library we will create
lib_extra_dirs = lib
lib_deps = 
    fabiobatsilva/ArduinoFake
lib_ldf_mode = deep+
build_flags = 
    -D UNIT_TEST
    -std=c++17
